### ISSUE TITLE
LiveReload for sass stylesheets

### ISSUE THREAD

**Issue by srph** [rstacruz/metalsmith-start#56]
Right now, it only reloads for files. Is this supported at the moment?

* I'm using `metalsmith-sass`.

**Comment by srph** [comment]
Irrelevant. I did not remove the `metalsmith-watch` and `metalsmith-serve` while running `metalsmith-start`.

**Comment by rstacruz** [comment]
gotcha! metalsmith-start should happily be able to deal with any CSS workflow; it operates on built files, not on source files.
